[package]
name = "seer"
version = "0.1.0"
edition = "2021"
authors = ["Jacob Andersen <19645494+jacobsandersen@users.noreply.github.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.8", features = ['http', 'axum'] }
worker-macros = { version = "0.8", features = ['http'] }
axum = { version = "0.8", default-features = false, features = ['json'] }
tower-service = "0.3.3"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
graphql_client = "0.16.0"
reqwest = { version = "0.13.3", features = ["json", "query"] }
chrono = "0.4.44"
