name = "seer"
main = "build/index.js"
compatibility_date = "2026-05-21"
workers_dev = false
preview_urls = false

[build]
command = "cargo install -q \"worker-build@^0.8\" && worker-build --release"

[[kv_namespaces]]
binding = "seer_cache"
id = "cd7d3d3e27c541f1ab528846da17abf1"

[[d1_databases]]
binding = "seer_geo"
database_name = "seer-geo"
database_id = "d183d0c2-082d-4a0b-b0fe-34fcdc7e9eb7"
remote = true

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
